# Generated by Django 4.2.2 on 2023-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_arrendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendar',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='arrendar',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
