# Generated by Django 4.2.2 on 2023-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ordenreparacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='tipo',
            field=models.IntegerField(choices=[['1', 'reparacion'], ['2', 'mantencion']]),
        ),
    ]
